# permissions for end users to view capideployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capideployment-viewer-role
rules:
- apiGroups:
  - capi.openshift.io
  resources:
  - capideployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capi.openshift.io
  resources:
  - capideployments/status
  verbs:
  - get
